CREATE TABLE burgers(
	id INT AUTO_INCREMENT NOT NULL,
  burger_name VARCHAR(250) NOT NULL,
  devoured BOOLEAN DEFAULT FALSE NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY(id)
);